### ISSUE TITLE
npm start error of development setup

### ISSUE THREAD

**Issue by chl87256** [plotly/react-chart-editor#1019]
![error](https://user-images.githubusercontent.com/61171990/76187822-bcd4f980-6219-11ea-83cd-c33045ef148a.PNG)
I did a development setup of react-chart-editor.
The installation proceeded to npm install, but after npm start, the error shown in the picture was displayed.
I tried several things but couldn't find the answer.
I thought it was a babel problem, so I upgraded and modified the index.js file, but it didn't work.
If you know how, please let me know. So thank you so much.

**Comment by dmt0** [comment]
Would you mind trying `yarn install` instead of `npm install`?
What is your node.js version?

**Comment by chl87256** [comment]
> ould you mind trying `yarn install` instead of

I'm using centos7 so I can't use yarn install. The version of node.js is 6.17.1

**Comment by dmt0** [comment]
node.js version is likely a problem. A lot of the dependencies are no longer supporting anything below v10. We're doing development with v12.

**Comment by chl87256** [comment]
> node.js version is likely a problem. A lot of the dependencies are no longer supporting anything below v10. We're doing development with v12.

thank you!! Yeah! I upgrade node js and fix other errors so it works fine.
