### ISSUE TITLE
ColorPicker widget doesn't display an alpha of 0 correctly 

### ISSUE THREAD

**Issue by bwarne** [plotly/react-chart-editor#1046]
**Setting the alpha of the ColorPicker widget to 0 correctly updates the alpha in the Plotly chart, but is shown as alpha of 100% in the Color Picker widget.**  

Currently the render() method of ColorPicker is stripping the alpha component when encoding selectedColor to a string and the alpha is 0.

https://github.com/plotly/react-chart-editor/blob/acdf2ce0cb0c8fdb5cf0a84f954fd4a50ad6a051/src/components/widgets/ColorPicker.js#L80

This appears to be causing problems with the react-color CustomPicker which interprets an rgbString lacking an explicit alpha as having an alpha set to 100%.  I'm not sure what the benefit is of removing the explicit alpha value but this issue appears to be fixed by changing the line to `selectedColor._a !== 1` so that the string encodes the alpha unless it is set to 1 or alternatively by always encoding the alpha by replacing lines 79-82 with `const rgbString = selectedColor.toRgbString();`.

The attached image shows the result of setting the alpha to 0, which the widget displays as 100, but is rendered as alpha 0 in the chart.
![image](https://user-images.githubusercontent.com/1149276/83922775-c8ab5b80-a735-11ea-88a2-b9e25514688c.png)

**Comment by dmt0** [comment]
Not sure why alpha was pinned to 0, it might've been because plotly.js didn't properly support alpha: https://github.com/plotly/plotly.js/issues/4120. That has been fixed now, so doing simply `const rgbString = selectedColor.toRgbString();` doesn't seem to cause any issues.
