### ISSUE TITLE
Incorrect styling for foldable section

### ISSUE THREAD

**Issue by johanbook** [plotly/react-chart-editor#1122]
I tried following the simple example and spinning up `react-chart-editor`, but it seems some styling is incorrect as seen in attached image.

![2021-02-15-103947_1920x1080_scrot](https://user-images.githubusercontent.com/13253042/107929759-64a28d80-6f7a-11eb-8d93-7341d53cf404.png)

I run the editor as

```tsx
import "react-chart-editor/lib/react-chart-editor.min.css";

import * as React from "react";
// @ts-ignore // exists no types for `react-chart-editor`
import PlotlyEditor from "react-chart-editor";

// @ts-ignore // types not available for `plotly.js/dist`
import plotly from "plotly.js/dist/plotly";

const EDITOR_CONFIG = { editable: true };

...


export function DataExplorer({
  data,
  dataSourceOptions,
}: SomeProps): React.ReactElement {
  const [state, setState] = React.useState({
    data: [],
    layout: {},
    frames: [],
  });

  return (
    <PlotlyEditor
      advancedTraceTypeSelector
      config={EDITOR_CONFIG}
      data={state.data}
      frames={state.frames}
      layout={state.layout}
      dataSources={data}
      dataSourceOptions={dataSourceOptions}
      plotly={plotly}
      onUpdate={(data: any, layout: any, frames: any) =>
        setState({ data, layout, frames })
      }
      useResizeHandler
    />
  );
}
```

With versions

    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "^4.0.1",

Have I missed something?

**Comment by dmt0** [comment]
@johanbook Could you try running it with React 16?

**Comment by johanbook** [comment]
I created a basic template with Create-React-App and then managed to run this code without the issue so it's likely some issue in some other part of my code base

**Comment by johanbook** [comment]
It seems to be due to the css property `box-sizing` set to `inherit`
