### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by ET-CS** [plotly/react-chart-editor#1133]
Hi.
react-chart-editor seems to be working with react 16+,
but there is a warning while installing dependencies:
```
yarn install
```

> warning "react-chart-editor > react-rangeslider@2.2.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".

seems that react-rangeslider@2.2.0 is requiring old react version.

react-rangeslider wasn't updated for 4 years. consider switching dependency.

**Comment by dmt0** [comment]
Thanks for letting us know @ET-CS :)
The project now is in rather passive maintenance mode, as we focus our efforts on other projects. `react-rangeslider` produces a warning during dependency install, but doesn't affect the functionality, so it's not something that we would prioritize fixing. If you or someone would like to give us a PR for that, we'd gladly review it though! [rc-slider](https://slider-react-component.vercel.app/demo/range) would be a good replacement candidate IMHO.

**Comment by ET-CS** [comment]
Thank you very much @dmt0 
I wish I had the time for it. wish someone would take up the glove :)

**Comment by ET-CS** [comment]
Working with warning
