### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [plotly/react-chart-editor#1156]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by nicolaskruchten** [comment]
Hello! You may email security@plot.ly :)

**Comment by zidingz** [comment]
Thanks! And if it'll save you time: https://github.com/plotly/react-chart-editor/pull/1157

**Comment by ready-research** [comment]
@nicolaskruchten Any update on this security issue? You can access the huntr link https://www.huntr.dev/bounties/4b5a9dfa-fcf3-40cb-8dba-ebccc1dfc11b/ and validate that with `Mark as valid`. Thanks.
