### ISSUE TITLE
LaTeX editor is broken

### ISSUE THREAD

**Issue by VeraZab** [plotly/react-chart-editor#267]
is:
![ex](https://user-images.githubusercontent.com/4257572/35297427-e238ad24-004c-11e8-9691-74071196e767.gif)

should be:
![ex](https://user-images.githubusercontent.com/4257572/35297554-56087126-004d-11e8-912b-53b2f22a0f84.gif)

**Comment by nicolaskruchten** [comment]
Can't replicate :)
