### ISSUE TITLE
Range Slider and Timescale Buttons panels in Axes

### ISSUE THREAD

**Issue by VeraZab** [plotly/react-chart-editor#330]
timescale buttons = rangeselector: https://plot.ly/javascript/reference/#layout-xaxis-rangeselector

**Comment by nicolaskruchten** [comment]
Just as a visual reminder for me of what this looks like in the Workspace today!

![image](https://user-images.githubusercontent.com/203523/36738150-d91d29b2-1baa-11e8-8b7b-437efe2d9c4f.png)
