### ISSUE TITLE
Folds cannot be used for generic use cases without hacking around visibility

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-chart-editor#386]
https://github.com/plotly/react-chart-editor/blob/master/src/components/containers/Fold.js#L29-L42

ensures that Folds will disappear if they contain children that are not plotly.js `attr` connected components. This makes it difficult for users (like the Batch Reporter) to construct their own custom panels.

**Comment by VeraZab** [comment]
yeah.. well I don't see a reason why we couldn't add support for a flag (ie `show`) on custom components, that would make the Fold show if it contains a child with that flag..
