### ISSUE TITLE
"Step Offset" input in StyleAxesPanel fails prop validation when axis is date

### ISSUE THREAD

**Issue by vdh** [plotly/react-chart-editor#404]
Related to #68 due to the default editor not yet supporting Date / Category types on axes.

When an axis has date values, the `Numeric` input for "Step Offset" in `StyleAxesPanel` fails prop validation for the `defaultValue` prop, due to the value being a date instead of a number.

**Comment by nicolaskruchten** [comment]
Ditto min/max on range
