### ISSUE TITLE
financial traces don't update right away

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#430]
The React update loop needs an extra kick for financial traces for some reason :(

**Comment by jackparmer** [comment]
@etpinard might have an idea

**Comment by nicolaskruchten** [comment]
I think this is an issue with `Plotly.react` not picking up changes the way we might expect. Trying to replicate outside of the editor.

**Comment by nicolaskruchten** [comment]
Was due to https://github.com/plotly/plotly.js/issues/2510
