### ISSUE TITLE
ModalBox in PanelHeader looks terrible

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#439]
In the Dev section ... the relevant CSS was added in #437 and it's rough with `--relative` etc... @aulneau do you have time to look at it? I really tried but couldn't make it work...

![image](https://user-images.githubusercontent.com/203523/38006316-7c3c9272-3212-11e8-8bf1-f7d49e7884d3.png)

**Comment by dmt0** [comment]
@nicolaskruchten 
This has been addressed in https://github.com/plotly/react-chart-editor/commit/80b863d1baf843b92dc2e2f742ac80066712aef1
