### ISSUE TITLE
Histogram bugs

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#443]
* switching from vertical to horizontal breaks the trace
* binning controls are missing

**Comment by bhogan-mitre** [comment]
Exposing controls for histogram binning would be very useful!  Is this something you'd consider a PR for, if it's not in the plans near-term?

**Comment by nicolaskruchten** [comment]
It's in the near-plan terms but any help is welcome :)

**Comment by bhogan-mitre** [comment]
Great, thank you!  If I try to implement anything, I will let you know.

**Comment by nicolaskruchten** [comment]
resolved in #496
