### ISSUE TITLE
Add Group/Filter transforms

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#444]
Blocked by https://github.com/plotly/plotly.js/issues/2508 and #439

**Comment by nicolaskruchten** [comment]
Transforms are out of dev but just for 'aggregate'. we need to resolve #439 to add group and filter :)

**Comment by bhogan-mitre** [comment]
I just went looking for the Filter transform in dev to try it out and couldn't find it.  Then I noticed the title change for this issue, implying that Filter needs to be added and not just cleaned up and moved out of dev.  

Is it still possible to use the Filter transform in some form?  If not, what is the prognosis for being able to do so in the future?

**Comment by nicolaskruchten** [comment]
It's definitely going to be in the UI, in the next month or two :)

**Comment by bhogan-mitre** [comment]
Nice, thanks for the info.  I think that will be really helpful when it gets plugged in.

**Comment by bhogan-mitre** [comment]
I've noticed some movement on this lately and it is looking good to my eye in some limited testing in the dev app.  Would it be possible to release a minor version to npm with the latest?  Thanks in advance for this capability!

**Comment by nicolaskruchten** [comment]
It's not quite ready for prime-time yet but as soon as it is it'll get merged up and released, have no fear :)

**Comment by bhogan-mitre** [comment]
Great, thank you!

**Comment by nicolaskruchten** [comment]
Released in version 0.18.0!

**Comment by bhogan-mitre** [comment]
Very exciting, thank you!

**Comment by nicolaskruchten** [comment]
We found one bug and will be rereleasing shortly but yeah, it is exciting :)
