### ISSUE TITLE
toggle editor visibility

### ISSUE THREAD

**Issue by bhogan-mitre** [plotly/react-chart-editor#448]
It would be useful to be able to hide the editor controls after a plot is setup, and just show the plot itself.  I am considering adding a `<Button/>` in a `<SingleSidebarItem/>` as the UI for this.  However, I don't see visibility options at the `<EditorControls/>` level, so it seems necessary to get deeper into the DOM in order to do this.  I wanted to check and make sure I'm not missing something obvious.  If not, I think this would be a nice feature to add.

Thank you for providing this great capability!  I am enjoying my first experiments using the React component.

**Comment by nicolaskruchten** [comment]
It sounds like a good feature, and we'd accept a PR for it if you wanted to implement it :)
