### ISSUE TITLE
Percy.io for Default Editor

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#463]
* in lieu of Jest tests
* a suite that loads up a list of mocks (in a clean window!) and then clicks through the panels in the menu and percy-snapshots each one. Let's do this for one mock of each supported trace-type, so we get a read on what things look like for a pie-chart, a ternary etc

**Comment by bpostlethwaite** [comment]
Sounds good. It will be trivial (minus race conditions...) to extend these going forward with a few extra clicks to get some data flow happening before snapshotting. I like it!

**Comment by nicolaskruchten** [comment]
Yeah. In principle though things *should* be path-independent, so most instances where clicking on stuff can get us into a weird state *should* be packed into plotly.js test-cases that call `react()` a few times. "*should*"

**Comment by nicolaskruchten** [comment]
https://percy.io/docs/clients/javascript/react

**Comment by nicolaskruchten** [comment]
in principle it should be as easy as grabbing something like this https://github.com/plotly/react-chart-editor/blob/master/src/components/containers/__tests__/Fold-test.js and calling it inside Percy and then just passing it different data instead of a fixture.

We don't want to snapshot the actual figure, just the editor

**Comment by nicolaskruchten** [comment]
Start in a local environment and once it's cool there we can move it to CI
