### ISSUE TITLE
Color by qualitative variable

### ISSUE THREAD

**Issue by bhogan-mitre** [plotly/react-chart-editor#465]
It would be nice to be able to color by a qualitative variable.  For example, in the dev app scatter plot when selecting color by `months`, the points change from default blue to black (all taking the same color).

It seems this may be a limitation in the underlying plotly.js.  But the user isn't going to know that as they are presented an option to color by that field.

I'm not sure the best way to approach this.  Is it dependent on the 'split by' transform being plugged in?  Or is there a way to map that qualitative variable to a numeric index behind the scenes?  The latter seems easier for the user, but it may be challenging/impossible to get a legend to communicate what the colors correspond to in that case.

**Comment by bhogan-mitre** [comment]
Great, thanks for the info!

**Comment by nicolaskruchten** [comment]
We'll be taking this up in https://github.com/plotly/plotly.js/issues/1747 and once done there we'll add support here... Closing for now.
