### ISSUE TITLE
Where i will add a chart type?

### ISSUE THREAD

**Issue by zhaodagang** [plotly/react-chart-editor#466]
I want to add a chart type on this panel , where add in source code ?
![13](https://user-images.githubusercontent.com/33817963/40093586-85d1129a-58f5-11e8-922e-bdf8017ef8a4.jpg)

**Comment by nicolaskruchten** [comment]
What kind of chart type are you wanting to add? At the moment we have added all of the supported trace-types in plotly.js...

**Comment by nicolaskruchten** [comment]
If you mean this kind of thing https://en.wikipedia.org/wiki/Sequence_diagram then you will have a very hard time, as it's not natively supported by plotly.js ... The architecture of this editor is designed to support plotly.js chart types.

**Comment by zhaodagang** [comment]
NO, not is like this  https://en.wikipedia.org/wiki/Sequence_diagram.
It is like this , chart data is realtime changed and time .
![11](https://user-images.githubusercontent.com/33817963/40401111-959f2450-5e77-11e8-85c2-05bc3706dcdb.jpg)
