### ISSUE TITLE
There some wrong after npm install 

### ISSUE THREAD

**Issue by zhaodagang** [plotly/react-chart-editor#467]
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\react-chart-editor\npm-debug.log

**Comment by nicolaskruchten** [comment]
Unfortunately I can't provide support for NPM installations of our dependencies... You'll have to try to install them individually and see what breaks.

**Comment by zhaodagang** [comment]
which version of node for installing react-chart-editor?

**Comment by zhaodagang** [comment]
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

node v8.11.1

**Comment by nicolaskruchten** [comment]
are you able to `npm install canvas` directly? If not, you'll have to get help from that project.

**Comment by nicolaskruchten** [comment]
Note to self: we may not need `canvas` after all... it's only there to suppress a warning

https://github.com/plotly/react-chart-editor/pull/294/commits/4b82f4456afea35116f9b7e78e68d6480cf9e495

**Comment by nicolaskruchten** [comment]
The `canvas` dependency has been removed.
