### ISSUE TITLE
Cannot install with npm from Visual Studio 2017/Windows

### ISSUE THREAD

**Issue by prenaut41** [plotly/react-chart-editor#469]
I'm unable to install react-chart-editor with npm.  
I'm not having problems installing any other packages, but I cannot install react-chart-editor.  

 Here is the log file that was generated:
[npm error log.txt](https://github.com/plotly/react-chart-editor/files/2010378/npm.error.log.txt)

**Comment by nicolaskruchten** [comment]
The errors at the bottom appear to be related to SSH. Are you able to SSH to github?

**Comment by prenaut41** [comment]
No idea how to test that.  
Is SSHing to github something that would be unique to react-chart-editor, since I don't seem to have issues with other packages?

**Comment by prenaut41** [comment]
Ah.  I'm on Windows Server 2012 R2.  Don't think I have a handy SSH client to test this easily.

**Comment by prenaut41** [comment]
If it's just that one dependency "draft-js-export-html", do you guys have any interest/plan in moving that to npm?

**Comment by prenaut41** [comment]
I've spent several hours trying to figure out how to work around this.  I thought I could just download the git repos for react-chart-editor and that draft-js-export-html dependency, edit the package.json files to load these from local disk and then run npm to grab everything.  This worked to load all the other dependencies for react-chart-editor (previously npm would hit the ssh error and then roll everything back to the initial state), but I have no idea how to get the git repos for these two which didn't come from npm to be converted into usable packages with the javascript and css modules exposed for importing so that webpack can find them when I try to build/bundle my app.  

There's apparently some build step I'm missing to get a 'usable' package for these two.   

Any ideas how I might be able to work around this issue to use this package from a Visual Studio 2017/Windows Dev environment (without changing my Dev environment)?

**Comment by nicolaskruchten** [comment]
@VeraZab what's the rationale for loading `draft-js-export-html` from github rather than NPM?

**Comment by VeraZab** [comment]
we needed this fix for the rich text editor: https://github.com/sstur/draft-js-utils/pull/93
I should have been in v1.2.0 of `draft-js-export-html`, but I think the author mispublished that version, and so that fix isn't there. There's an old open issue for it: https://github.com/sstur/draft-js-utils/issues/111

**Comment by nicolaskruchten** [comment]
OK, version 0.16.3 of this package now depends only on modules hosted by NPM, not by Github!
