### ISSUE TITLE
[Question] Custom Attrs?

### ISSUE THREAD

**Issue by dmossie** [plotly/react-chart-editor#470]
Hey there, I am wondering if it is possible to add custom fields with custom attrs to the react chart editor.

What I am trying to do specifically, is add a new drop down to the Trace Menu. This dropdown will influence the data options for X and Y from our database.

Example:
![untitled](https://user-images.githubusercontent.com/30665550/40261112-b381e402-5ab3-11e8-90d6-6e9a0fde729f.png)

I noticed the Dropdown and the DataSelector require an attr field. The attr field would be nice to use if it stores the data in the chart, however I do not want it to influence anything on the chart directly.

Is it possible to create custom attrs so that I can add new custom fields to the chart editor?

**Comment by nicolaskruchten** [comment]
You can add custom fields and widgets, you just can't use the `attr` prop, otherwise the framework will hide them as they won't be found in `_fullData` or `_fullLayout` from plotly.js...

**Comment by dmossie** [comment]
Hey @nicolaskruchten , thanks for the reply!
I find without the attr prop, the fields will not show up at all.
Example:
```
            <PlotlySection name={_('TestSection')}>
                <DataSelector label={_('TestSelector')}/>
                <Dropdown
                label={_('TestDropdown')}
                clearable={false}
                options={[
                    { label: _('Auto'), value: 'auto' },
                    { label: _('45'), value: 45 },
                    { label: _('90'), value: 90 },
                    { label: _('135'), value: 135 },
                    { label: _('180'), value: 180 },
                ]}
                />
            </PlotlySection>
```

I am assuming I can not use these components at all and that I should make my own? This might make sense as I will need an onChange function.

The reason I am asking is it would be nice to keep our components looking the same as plotlys components visually.

**Comment by nicolaskruchten** [comment]
Ah, sorry, now that I look at how we've done this in the past, we've not used the exported *fields* but the *widgets* and then rewrapped them in `<Field>` but not called `connectToContainer()` on them. The resulting component has the `<Field>` styling but not the visibility rules tied to `attr`. We had at the time (3 weeks ago, at the office) discussed the idea of exporting the unconnected fields as well as the connected ones for this exact use-case and in fact we should. If you submitted a PR that did just that we'd likely approve it and re-release in a flash :)

To answer your other question: you cannot create your own `attr`s as those are defined in the [plotly.js schema](https://plot.ly/javascript/reference/)

/cc @VeraZab

**Comment by dmossie** [comment]
Hey @nicolaskruchten and @VeraZab. I am going to take a shot at implementing this. I am having a few issues though. Is there someone I can contact about this for support?

**Comment by nicolaskruchten** [comment]
This issue is probably a good place :)

**Comment by dmossie** [comment]
Ok thank you.

I am having trouble testing these new components I am creating.

I was wondering if someone could help point me in the right direction to easily test these new components to see if they work. What is the go to way to do this at plotly?

Also I did an 'npm install' in the forked repository, and it seems that "canvas": "^1.6.9" is breaking it. It breaks on both windows and linux for me.

**Comment by nicolaskruchten** [comment]
Yeah we should see if we can remove `canvas` and just live with the warnings that it's meant to suppress. Those warnings come in the `jest` tests which are basically the answer to your other question. The various component directories have some test files which you can use as templates, like this one for example: https://github.com/plotly/react-chart-editor/blob/master/src/components/fields/__tests__/CanvasSize-test.js

**Comment by dmossie** [comment]
Is there a way to test it visually? I am wondering how to see my new components easily in a react chart editor after I have implemented them. Perhaps I need to convert the source code into an npm package some how?

**Comment by nicolaskruchten** [comment]
I'd recommend adding them to one of the demo apps or creating your own demo app in the same package, even if you don't commit that app.

**Comment by bhogan-mitre** [comment]
I found the included dev app (with hot reloading) super helpful when working towards a recent PR as well.

**Comment by dmossie** [comment]
Thanks for the feedback guys. I tried making a new demo in /examples/dans-demo (copied from demo).
I see in the package.json, it requires react-chart-editor.

 I want it to use my chart editor, so on the command line I typed 'npm install C:\Users\path\to\react-chart-editor'.

This caused my package.json to look like this:
```
{
  "name": "demo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "plotly.js": "^1.35.0",
    "react": "^16.2.0",
    "react-chart-editor": "file:../..",
    "react-dom": "^16.2.0",
    "react-scripts": "1.0.17"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build"
  },
  "homepage": "http://plotly.github.io/react-chart-editor",
  "devDependencies": {
    "gh-pages": "^1.1.0"
  }
}
```

 It seemed to successfully install, however when I run 'npm start' I get this error:

`Module not found: Can't resolve 'react-chart-editor' in 'C:\Users\Daniel\Documents\repo\react-chart-editor\examples\dans-demo\src'`

Does anyone know how to set this up properly?

**Comment by dmossie** [comment]
Hey @nicolaskruchten and @bhogan-mitre - do either of you guys know how to do this?

**Comment by nicolaskruchten** [comment]
I think your best bet would indeed be to use the existing `dev` app if this is what you're trying to do... It's already set up to reference a relative copy of react-chart-editor and has hot-reloading etc. That's probably the advice I should have given you above and I was likely thinking 'dev' when I typed 'demo', sorry!

**Comment by dmossie** [comment]
Thanks for your help guys, I made a custom drop down and created a pull request.
