### ISSUE TITLE
[Question] AxisCreator

### ISSUE THREAD

**Issue by dmossie** [plotly/react-chart-editor#472]
Hey there,

I am trying to add a secondary y-axis to my custom react chart editor.
I noticed this as an existing feature [here](https://plotly.github.io/react-chart-editor/) at multiple_axes_double.json under "Axes To Use"

However I am having trouble with a few things:
1) Why does "Axes To Use" only show up under certain "mocks" and not all of them?
2) In the source for GraphCreatePanel.js I see this:
```
      <PlotlySection name={_('Axes to Use')}>
        <AxisCreator attr="fake_attr" />
      </PlotlySection>
```
How does this work if the attr is "fake_attr"? Maybe it doesn't as it does not appear when I use the DefaultEditor? (but I see it in the demo with multiple_axes_double.json)

3) AxisCreator is not being exported in src/index.js, (but it is in ./components). Is there any reason for this? Could it be exported as well so I could use it with my custom editor?

Thank you

**Comment by nicolaskruchten** [comment]
1. mocks are basically prebuilt figure JSON definitions, which contain traces of certain types (i.e. cartesian subplots only, per the comment in the source file). Not all trace-types are compatible with multiple axes, so the `AxesCreator` doesn't appear in all cases. Notably, it doesn't appear when you have only a single trace of a given type.
2. IIRC this was a hack to get it to appear despite it not being mapped directly to an underlying value in `_fullData` or `_fullLayout`: we needed an `attr` but it couldn't be one that was actually ever present in the `_full*`.
3. At the moment this component is fairly specific to the place/way it's being used in the `DefaultEditor` (as you can see it takes a bit of effort to make it appear/disappear at the appropriate times) so I don't think we want to export it more globally or have to document its behaviour at this time...

More generally, building a usable UX around plotly.js' current implementation of subplots is pretty tricky, and the current implementation is rather more experimental than the rest of this package :)

**Comment by dmossie** [comment]
Hey @nicolaskruchten, thank you again for your response.

Do you think that it will be a feature to add secondary y-axis to custom editors at some point soon?

I am putting together an editor for my company and we like the custom editor as we can remove features we don't want - however a secondary Y axis is an import feature to us.

**Comment by nicolaskruchten** [comment]
I definitely get where you're coming from! If the current one meets your needs you can always import it directly from `react-chart-editor/path/to/component.js` even if it's not directly exported, but the current implementation is a bit brittle so it's kind of an "at your own risk" situation. I'm afraid I don't have a timeline for when this will be considered robust enough to be supported officially.

I should add that if we were to enter into a commercial relationship, whereby we would either build or help build your custom editor to your specs, we would be able to offer long-term support, upgrades etc, in case this is something your company is interested in: https://plot.ly/products/consulting-and-oem/

**Comment by dmossie** [comment]
Great! Thank you
