### ISSUE TITLE
Visibility bugs in Axes panel 

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#473]
One way to replicate is to load the `ternary-lines` mock :)

![image](https://user-images.githubusercontent.com/203523/40552546-016a4722-600e-11e8-838f-e6fabd6c5940.png)

**Comment by nicolaskruchten** [comment]
OK, I poked at this for a bit and I think we can move the `fixedrange` element into the Range fold, and make the Hover Projections fold only appear on `cartesian` subplots.

**Comment by dmt0** [comment]
And perhaps make _Layout_ not appear on `ternary`?

**Comment by dmt0** [comment]
Making Hover Projections fold only appear on `cartesian` subplots, makes it disappear on Scatter.
