### ISSUE TITLE
Is there a Chinese version?

### ISSUE THREAD

**Issue by zhaodagang** [plotly/react-chart-editor#475]
Is there a Chinese version?
Or how to sinicize?

**Comment by nicolaskruchten** [comment]
We don't have a Chinese locale file, but you'd want to add one in here: https://github.com/plotly/react-chart-editor/tree/master/src/locales and then set the `locale` prop: https://github.com/plotly/react-chart-editor/blob/master/src/PlotlyEditor.js#L67

**Comment by zhaodagang** [comment]
If i need chinese version, should  i need change /locales/xx.js file ?

**Comment by zhaodagang** [comment]
Is not this app userd to locales/xx.js  file ?

like this:
import locale from 'locales'

<PlotlyEditor
locale={locale}
/>

**Comment by zhaodagang** [comment]
like this:
import locale from 'locales'

<PlotlyEditor
locale={locale}
/>

**Comment by nicolaskruchten** [comment]
You need to provide the locale name, not object, so just `"en"` for example.

The `"xx"` locale is a special locale with lots of spacing around the tokens for layout testing.

**Comment by nicolaskruchten** [comment]
Also, a sidenote: please do not post a comment and then edit it multiple times, completely changing its contents. Every time you post a comment or edit it, a notification is generated in our systems and it's hard for us to keep track of what you're asking/saying.

**Comment by zhaodagang** [comment]
Why doesn't it work?

**Comment by zhaodagang** [comment]
If I change the Chinese version manually, how should I change it?
