### ISSUE TITLE
Transforms don't work for many trace types

### ISSUE THREAD

**Issue by dmt0** [plotly/react-chart-editor#489]
As of now transforms work for the following trace types:
- Scatter, Bar, Line, Area
- 3D scatter
- All Distributions

Partially work for:
- Scatter GL
- All Financials

For the rest of the trace types there is either no action when you try to create a transform or a console error.

**Comment by nicolaskruchten** [comment]
OK, let's add some conditional code that prevents users from adding transforms to non-scatter traces for now, which is I believe what the current workspace does. It can look/behave a bit like the color bars UX where the fold is there but has a special 'empty' content.

**Comment by nicolaskruchten** [comment]
Can you explain "partially work" for `scattergl` ?

**Comment by dmt0** [comment]
At this point `scattergl` seems to work.

**Comment by bhogan-mitre** [comment]
I have noticed some weird behavior with `scattergl` and filter transforms.  I am using `Plotly.restyle` to update the filter value and noticed that some of the markers are hidden.  The data points are there and are being filtered correctly, they are just not all displaying properly.  For example, I can hover over where the points _should_ be and get the data block to display but the marker itself is not there.  If I switch back to `scatter`, I can see all of the markers.  After filter updates, I am generally seeing only one or two markers with `scattergl` where there should be ~50 or so .

I am not sure how best to feed this back to you with a reproducible example.  But let me know if you have any ideas.

**Comment by nicolaskruchten** [comment]
If you're using plotly.js directly with `restyle` then you'll probably have to report the issue over in that repo rather than here... `react-chart-editor` interacts with plotly.js via `react-plotly.js` so we're a couple of layers removed :)

**Comment by bhogan-mitre** [comment]
Good point, thanks.  I will try to isolate the issue and report in plotly.js.
