### ISSUE TITLE
Switching between trace types when data sources are selected produces errors

### ISSUE THREAD

**Issue by dmt0** [plotly/react-chart-editor#490]
Create a trace, select data sources, change trace type. In many cases there will be a console error.

**Comment by nicolaskruchten** [comment]
Can you firm up this issue please by providing specific from- and to- trace-types that cause this (at least one)? It's too vague to be actionable at this point :)

**Comment by dmt0** [comment]
- table -> contour
- table -> pie
- table -> scatter
- contour -> polar scatter (gl)
- contour -> scatter

Seems to happen whenever one of the DataSelectors on a 'from' trace is multi-value / 2D

**Comment by nicolaskruchten** [comment]
Makes sense. Can you take a stab at fixing it?

**Comment by dmt0** [comment]
Basically, when we switch from, say, table to scatter, we're still rendering data selector with old `attr` `header.values`, but `container` already switch to `scatter`, so `is2d` is computed as `false`, so Dropdown gets an incorrect input, which results in a warning. But than it rerenders immediately with correct value, so no harm is done here.
