### ISSUE TITLE
Additional aggregation functions

### ISSUE THREAD

**Issue by bhogan-mitre** [plotly/react-chart-editor#508]
Coming soon to plotly.js are additional aggregation functions `range` and `change`: https://github.com/plotly/plotly.js/pull/2764

It seems like a fairly straight-forward update to accommodate those functions here, but that we'd need to wait until plotly.js cuts a release and coordinate with that.

**Comment by nicolaskruchten** [comment]
Nice! Thanks for the contributions :)

We should have transforms merged into this repo very soon, and as soon as the new plotly.js is released with these new functions we'd be happy to accept a PR that adds support here as well!

**Comment by bhogan-mitre** [comment]
Are we ready for this now that plotly.js has released v1.39.0?  Does anything need to happen with react-plotly, or would you be ready for a PR here?

**Comment by nicolaskruchten** [comment]
A PR here would work just fine, you'll just have to bump plotly.js in `package.json` :)
