### ISSUE TITLE
deleting a trace and adding one populates editor with deleted trace

### ISSUE THREAD

**Issue by VeraZab** [plotly/react-chart-editor#509]

**Comment by nicolaskruchten** [comment]
I wonder if somehow the `useAsDefaultTrace` default value isn't getting mutated somewhere along the line by plotly.js... And the reason I don't see it in Amex is that I'm actually overwriting it?

**Comment by nicolaskruchten** [comment]
I wonder if the default value for  `useAsDefaultTrace` isn't getting mutated somewhere along the line and the reason I'm not seeing it in jupyterlab is that I'm overriding it?
