### ISSUE TITLE
systematically compare workspace and editor attr coverage

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#524]
* @dmt0 and @nicolaskruchten will go trace type by trace type and compare workspace and editor
* @VeraZab will do it code-wise

**Comment by dmt0** [comment]
So far I went through Scatter, Bar, Line, Area, and Pie, it resulted in https://github.com/plotly/react-chart-editor/pull/561. Will also raise a few issues that were not included.

**Comment by dmt0** [comment]
Went through all Geo/Mapbox, 3d, Ternary, that resulted in #589 and #660

**Comment by dmt0** [comment]
Went through Mapbox
