### ISSUE TITLE
Can't change colors of pie chart slices

### ISSUE THREAD

**Issue by jackparmer** [plotly/react-chart-editor#538]
I might be missing something in the [demo app](https://plotly.github.io/react-chart-editor/), but it doesn't seem that one can change the pie chart slice colors:

![image](https://user-images.githubusercontent.com/1865834/42129432-3761d17e-7c92-11e8-87e0-8ed45808d17d.png)

![image](https://user-images.githubusercontent.com/1865834/42129433-4ae414f0-7c92-11e8-99ab-dde560237eba.png)

**Comment by nicolaskruchten** [comment]
Indeed. I'm removing the 'bug' label as this is more of a "parity"/missing-attr thing, and I'm filing it in the appropriate column  in the project :)

**Comment by nicolaskruchten** [comment]
What's needed here is a new `PieColors` widget linked to `marker.colors` that should live in the `<TraceMarkerSection>`:

* it should output a clean array of colors of the right length, not an array of arrays like the normal colorscale picker
* if a set of colors already exists in the figure it should read them in and display them correctly
