### ISSUE TITLE
Can't create line/scatter plot, then add bar chart

### ISSUE THREAD

**Issue by dmossie** [plotly/react-chart-editor#541]
If you add a trace (line, scatter etc), then add a second trace as a bar chart, it breaks and displays the following error in the console:

![untitled](https://user-images.githubusercontent.com/30665550/42250721-d0a08c66-7ee7-11e8-993c-e55706ab27be.png)

**Comment by nicolaskruchten** [comment]
should be fixed in the next release this afternoon :)

**Comment by nicolaskruchten** [comment]
Resolved in version 0.18.0!

**Comment by dmossie** [comment]
awesome, thanks!
