### ISSUE TITLE
Enabling transforms for histogram, box, violin

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#556]
Could we try to enable transforms for these three trace types? If it doesn't work, can we try to figure out why?

**Comment by bhogan-mitre** [comment]
I was just about to open an issue on this.  I would suggest line plot as well as the trace types you listed.  There is nothing preventing filter transforms for histogram, box, line (and presumably violin), and that would be very useful for me.

Could we enable filtering, even if aggregate (or split) doesn't make sense for those types?

**Comment by nicolaskruchten** [comment]
Line is already supported AFAIK because it's a specialization of scatter. And yes, what I'd like is all three transform types for these three trace-types.
