### ISSUE TITLE
issue with custom editor and Aggregations 

### ISSUE THREAD

**Issue by bhogan-mitre** [plotly/react-chart-editor#564]
This is likely user error, but I am trying to use a custom editor and I'm having trouble getting the `Aggregations` component to display properly.

I am basically trying to use a `GraphTransformsPanel`, modified with an extra `Info` component.

```
          <TraceAccordion group='Graph' name='Transforms'>
            <TransformAccordion>
                <Radio
                  attr="enabled"
                  options={[
                    {label: 'Enabled', value: true},
                    {label: 'Disabled', value: false},
                  ]}
                />
                <DataSelector label='By' attr="groups" />

                <DataSelector label='Target' attr="target" />
                <FilterOperation label='Operator' attr="operation" />
                <FilterValue label='Value' attr="value" />
                <PlotlySection name='Aggregations' attr="aggregations">
                    <Aggregations />
                </PlotlySection>

                <Info>helpful text</Info>
            </TransformAccordion>
          </TraceAccordion>
``` 

The `Aggregations` component is displaying inside of what appears to be a nested `TransformAccordion`.  
![2018-07-09_09-08-43](https://user-images.githubusercontent.com/32336739/42452595-7d160600-8358-11e8-9e12-98a8fa2dc6c4.png)

That extra nesting is occurring even if other transform types are selected, for example Split in the screenshot below.
![2018-07-09_09-08-07](https://user-images.githubusercontent.com/32336739/42452675-bcdf52fa-8358-11e8-980b-423aecf3e20b.png)

Is there something I can do to get the necessary container or context information passed through to `Aggregations`?

As an aside, is there a way to get that `Info` component to only show up for certain transforms (e.g. Filter)?

**Comment by dmt0** [comment]
Not sure why this nesting is happening, I'd need to see the context in which you use that code to understand it. Can you post something on github that I could clone and run?

As to having `Info` only show up for certain transforms, I'd do it in `TransformAccordion`. Something like this:

```JSX
    const content =
      filteredTransforms.length &&
      filteredTransforms.map((tr, i) => (
        <TransformFold
          key={i}
          transformIndex={i}
          name={`${
            transformTypes.filter(({type}) => type === tr.type)[0].label
          }${transformBy && transformBy[i]}`}
          canDelete={true}
        >
          {children}
          {filteredTransforms[i].type === 'filter' ? (
            <Info>This is a filter</Info>
          ) : null}
        </TransformFold>
      ));
```

Hope that helps. :)

**Comment by bhogan-mitre** [comment]
Sure, thanks for offering to take a look!  The screenshots above were from modifying the dev app in place.

Here's a standalone example: https://github.com/bhogan-mitre/custom-editor
Interestingly, this attempt has an error preventing the plot from displaying after aggregations are added.
```
index.js:2177 Error while plotting: TypeError: Cannot read property 'newPlot' of undefined
    at factory.js:66
```

The aggregations block is still displaying for each aggregation type, although its contents are empty.  For example, see this Filter setup:

![2018-07-10_21-13-36](https://user-images.githubusercontent.com/32336739/42545476-36523f3e-8486-11e8-873d-79fb7766cf6f.png)

Thanks for the tip on the conditional `Info` block as well!

**Comment by bhogan-mitre** [comment]
Revisiting this one.  I got around my issue by creating a custom `GraphTransformsPanel`, and including that in the custom editor.  That set the context properly, where my previous attempt using `<TransformAccordion>` and `<Aggregations />` a la carte did not.  

If anyone is interested, my sample app with those changes is here: https://github.com/bhogan-mitre/custom-editor

Thanks for the tip on the conditional `<Info>` block as well, that was very helpful @dmt0!
