### ISSUE TITLE
feature: provide ability to set hovermode

### ISSUE THREAD

**Issue by n-riesco** [plotly/react-chart-editor#567]
See [here](https://community.plot.ly/t/cant-color-based-on-column-value/11602/2) an example of a chart that would benefit from setting hovermode to closest.

**Comment by nicolaskruchten** [comment]
Yep, we're adding it, but it's also always available on the modebar

**Comment by nicolaskruchten** [comment]
Actually hovermode is already exposed in the Layout panel, but #561 rounds out support for its options.
