### ISSUE TITLE
Subplots for all trace types

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#580]
In an ideal world, users should be able to create and manipulate all subplot variants that plotly.js can create. Certainly it should be possible to create multiple `pie` subplots for example.

**Comment by nicolaskruchten** [comment]
Types of subplots:
* 2d
* 3d
* geo
* pie
* polar
* ternary
* table/parcoords/splom??

Examples of how to subplot various combos of these:
* geo_africa-insets.json (multiple geo)
* polar_subplots.json (multiple polar)
* https://plot.ly/~nicolaskruchten/144/#code (geo + 3d + 2d)
* https://plot.ly/python/pie-charts/ (has dual-pies)
* ternary???

**Comment by nicolaskruchten** [comment]
Should we consider a new "Subplots" panel which somehow figures out all the subplots and allows us to position them with vertical/horizontal sliders?

**Comment by nicolaskruchten** [comment]
Step 1: let's collect in a comment in this issue information about where in the figure the subplot domain information lives for all the different types of subplots listed above :)

**Comment by dmt0** [comment]
So it seems domain can be either in layout or in data and it can be either an array of two values or an object:

layout.axisname.domain = [0.65, 0.95]
xaxis, yaxis

layout.axisname.domain = {“y”: [0, 0.9], "x": [0, 0.55]}
geo, polar, scene, ternary

data[x].domain = {"x": [0, 0.48]}
parcoords, pie, table

**Comment by dmt0** [comment]
Having an extra panel for this would allow us to do things without magic and keep things close to ploty.js.

But with a bit of magic... we could make a radio button in the GraphCreatePanel with choices like "Merged" | "Separate subplot" | "Move to the side within same subplot" (with better wording of course), and once that radio is selected, the new axes are created automatically as needed and sliders appear that allow to move your subplot around. That would replace current AxesSelector.

**Comment by nicolaskruchten** [comment]
OK, so here's the spec for how to handle this issue:

* We add a new Style/Subplots panel, which renders as a Subplot Accordion, which has a fold per subplot. 
* The list of subplots is defined to be the union of all (xaxis-yaxis pairs which share a trace, scenes, polars, ternarys, geos, pie-traces, table-traces). 
* Each fold in this accordion has (minimally) 4 sliders: horizontal/vertical min/max domain. (we can turn these into two-knob sliders later)
* The x-y folds will need to handle the 'overlaying' thing, and the overlaying/domain stuff will be removed from the Layout fold of the Style/Axes panel
* The Create/Traces folds for 3d/geo/polar/ternary will need a new custom widget to set which scene/geo/polar/ternary they are attached to, similar to the current way we deal with xy axes in scatter

Once this is done, there will be a (long!) series of clicks whereby it will be possible to create and position a figure which can contain arbitrary combinations of subplots of any currently-supported type! (i.e. not parcoords, splom, sankey... yet :)

**Comment by nicolaskruchten** [comment]
Finally:

* Any attr that lives in `layout.(scene*|geo*|polar*|ternary*)` needs to be moved/added to the corresponding subplot fold. So stuff like `aspectratio` and so on. This alone justifies the addition of this panel: the fact that these attributes otherwise have no home or can only apply to the first subplot :)

**Comment by dmt0** [comment]
If I create a choropleth trace and an atlas map trace, they reuse the same layout.geo object, so domain is shared

**Comment by nicolaskruchten** [comment]
right, but we can change one of them to use a second `geo` right? `geo2` or something, just like we can have multiple `scenes` and so on?

**Comment by nicolaskruchten** [comment]
This mock just blows my mind: https://rreusser.github.io/plotly-mock-viewer/#grid_subplot_types

So much easier to use grids instead of percentage layouts. We should about how this feature (which I only just learned about!) impacts this design...

/cc @VeraZab check out that mock!

**Comment by nicolaskruchten** [comment]
Subsumes #440

**Comment by dmt0** [comment]
Once https://github.com/plotly/react-chart-editor/pull/610 is merged, the only thing left here is to move geo.*, scene.* stuff into subplot panel OR create some SubpotConnectedSections in GraphCreatePanel

**Comment by nicolaskruchten** [comment]
OK, so let's move all the `polar.<>`, `geo.<>`, `ternary.<>` and `scene.<>` into the corresponding subplot folds in Graph/Subplots in an "Options" section. While we're in there let's make sure the `bgcolor` option is there where supported :)

Note that this means that the "Geo Layout" fold will disappear and thus make the geo subplot folds huge, and we'll also have to lightly adapt the `shamefullyAdjustGeo` stuff to work with e.g. `geo2` and so on.
