### ISSUE TITLE
Migrate from percy react to storybook

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#585]
Ugh.

**Comment by nicolaskruchten** [comment]
Nice job on this! :)

**Comment by nicolaskruchten** [comment]
What's the command for running the storybook locally? Can you update the readme as well please?

**Comment by dmt0** [comment]
That would be `npm run storybook`
I'm not sure, how useful it is to users of this library beside the percy integration. So not sure if we really need it in readme.
