### ISSUE TITLE
Standardize colorscale attrs

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#606]
Right now we support some nice color-related attrs in Style/Trace for the surface/heatmap traces that should also appear in scatter and other non-covering traces, like `showscale`, `reversescale`, `cmin`, `cauto` etc. They're mapped to `marker.X` in the latter case, and for the various scatter options, they also exist for `line.X`.

Also, there's some weirdness in Heatmap traces around `zauto` which should be resolved similarly...

Surface (`c*`):

![image](https://user-images.githubusercontent.com/203523/43142230-ecc72ab4-8f25-11e8-8e03-6650824f2b48.png)

Heatmap (`z*`):

![image](https://user-images.githubusercontent.com/203523/43142019-699580b4-8f25-11e8-9c85-da8eb3526357.png)

Scatter (`marker.c* missing`):

![image](https://user-images.githubusercontent.com/203523/43142039-744a8522-8f25-11e8-86bb-d0e43a332d77.png)

**Comment by nicolaskruchten** [comment]
See also #516

**Comment by dmt0** [comment]
So in #605 I added all options, but still need to replace ColorPickers with MarkerColor. MarkerColor needs to be reworked for this to happen, as it makes assumptions about the attr and it's nontrivial to fix that...

**Comment by nicolaskruchten** [comment]
@dmt0 does the comment above still apply after our chat of 30min ago ?

**Comment by nicolaskruchten** [comment]
(note: we're not currently supporting `line.color` as anything other than constant so plz ignore that part of this issue!)
