### ISSUE TITLE
Type-specific fields appearing inappopriately

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#624]
See

![image](https://user-images.githubusercontent.com/203523/43544177-29a64da4-95a0-11e8-9f02-a3b22fd4d585.png)

**Comment by dmt0** [comment]
Some of these fields are subplot-specific, those can be resolved when we move them either into subplotConnected sections of to subplots panel

**Comment by nicolaskruchten** [comment]
OK, let's finish off #580 and the related #440 stuff first and then we'll see if this still happens. I'll move error bars into Style/Traces anyway.
