### ISSUE TITLE
Axis "side" controls

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#672]
Right now in the Axes panel we have controls for various "Sides" that always show bottom/top/left/right and it's weird because in X mode it should be just left/right and in Y mode just bottom/top. In "grouped" mode that widget should just not appear as there's no option that makes sense unless we build a complex custom component that controls x and y separately which I don't want to do :)

**Comment by dmt0** [comment]
We copied it over into subplots panel already, but not the other relevant elements. And there is already a derived component that solves it, but only in subplots panel. Shall we keep it only in Axes panel?
