### ISSUE TITLE
Provide an input for Tick Format

### ISSUE THREAD

**Issue by timopulkkinen** [plotly/react-chart-editor#685]
Hi,

it seems that there is no input field for tick format in d3 formatting mini-language (at least I can't find any). Could you add this to the editor?

**Comment by nicolaskruchten** [comment]
Hi!

Is your use-case covered by #686 or did you have another thing in mind for this issue?

Here is what the current version contains for tick formatting:

![image](https://user-images.githubusercontent.com/203523/44104098-c9c6543a-9fa2-11e8-816a-37c264b376d6.png)

**Comment by timopulkkinen** [comment]
I was thinking more of a mask input for the tick labels, so that I could input, for example, a date formatting mask like %yyyy-%mm. This way user would have greater control on the actual tick label displayed.

**Comment by nicolaskruchten** [comment]
Thanks for the suggestion! This editor wraps plotly.js pretty directly, and unfortunately I don't believe plotly.js supports such a parameter, so to get this done we would need a feature request over at https://github.com/plotly/plotly.js and get that merged in, and then we could add editor support for it.

**Comment by timopulkkinen** [comment]
Ok, should I create one there?

**Comment by nicolaskruchten** [comment]
Yep, that's probably a good idea!

**Comment by bhogan-mitre** [comment]
It looks like `tickformat` exists as an axis layout option in plotly.js: https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/layout_attributes.js#L504

Would that work to expose as an option in the editor?

**Comment by timopulkkinen** [comment]
> It looks like `tickformat` exists as an axis layout option in plotly.js: https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/layout_attributes.js#L504
> 
> Would that work to expose as an option in the editor?

Yes, this is exactly what I'm after!

**Comment by bhogan-mitre** [comment]
On a related note, would it be possible to make the date suffix on the first tick optional?  That may be buried within plotly.js as well.

![2018-09-27_06-21-33](https://user-images.githubusercontent.com/32336739/46157584-11fd9500-c24a-11e8-8e92-bd79c80898ab.png)

I really like having the date suffix there most of the time.  However when the data are actually small time intervals, I'd like to be able to hide the epoch date that shows up.  In the example above, the metric is on the order of 20 minutes.  That could be more clear by enabling `tickformat` and not showing the "Jan 1, 1970" in this case.

**Comment by bhogan-mitre** [comment]
> I'm not sure about adding such a "programmery" widget... I don't know where we would provide the documentation for what's allowed in that textbox etc.

How does this relate to [this writeup](https://help.plot.ly/date-format-and-time-series/#step-4-custom-formats-for-your-graph) and the "Custom date format" shown on that page (presumably from an earlier editor)? 
![axis labels](https://help.plot.ly/static/images/dates-time-series-and-timestamp/axes-labels.png)

If it's labeled "Custom date format" with a tooltip having an example time format or two, would that work?

**Comment by nicolaskruchten** [comment]
Hehe that is indeed a very old tutorial that refers to version 1 of our editor (this react-chart-editor is essentially version 3). 

I'll think about what to do here. Maybe I'll do what I did with the `separators` in Style/General and provide a number of built-ins or something.

**Comment by nicolaskruchten** [comment]
Note that there are a number of usability/context issues here: plotly.js doesn't provide a default value for this field as far as I can tell, and the applicable mini-language depends on the axis type (numerical vs date) so a fair bit of logic needs to be coded in order to provide decent feedback to the user about what's allowed when.

**Comment by bhogan-mitre** [comment]
Yeah, I see where you're coming from.  I noticed that the Exponents dropdown is only displayed for numeric axes (although I'm not sure how that happens behind the scenes).  Could a prospective date format input work similarly, and only display for date axes? That could take care of the when it's allowed piece.  For what is allowed, could a tooltip suggesting a couple examples be sufficient?

**Comment by nicolaskruchten** [comment]
> Could a prospective date format input work similarly, and only display for date axes?

Unfortunately not because it's the same `tickformat` that applies to both number formatting and date formatting.

> For what is allowed, could a tooltip suggesting a couple examples be sufficient?

It could, yes, but we don't have any facility in the framework right now for per-input tooltips of this kind, so we'd be adding it in just for this, which doesn't feel great.

**Comment by nicolaskruchten** [comment]
I could represent this as a simple dropdown with two options: auto/custom, similar to the way the prefix and suffix inputs work. Custom would allow the user to type this special mini-language and would override and hide the show-exponents, exponent-format and separate-thousands inputs automatically, but it still feels very out of place in this editor to have this totally opaque input field that allows this cryptic mini-programming language in the middle of what is an otherwise almost totally mouse-drive interface.

**Comment by nicolaskruchten** [comment]
OK, how about something like this? I've added a dropdown with "simple" and "advanced" modes and things more or less auto-hide as expected...

Default:

![image](https://user-images.githubusercontent.com/203523/46577696-66c3ad00-c9ba-11e8-81a8-0fb78e21a75e.png)

Override:

![image](https://user-images.githubusercontent.com/203523/46577700-70e5ab80-c9ba-11e8-9b7f-f1286a0d03f8.png)

**Comment by nicolaskruchten** [comment]
Ugh, `s` is a valid number format but not date format unfortunately. Won't be quite that easy :)

**Comment by nicolaskruchten** [comment]
OK, there we go, conditional options for `date` and non-`date` axis types. You can try it here #762

**Comment by bhogan-mitre** [comment]
Thanks for playing around with this!!  I appreciate the complexities here more, now that I see it flipping between `d3-format` and `d3-time-format` in advanced mode depending on type.

I think the advanced formatting options for numeric axes will be useful in some cases, and this looks like it will cover my intent with date axes nicely as well.  Thank you!

**Comment by nicolaskruchten** [comment]
Thanks for keeping the pressure up. I don't love the solution but it works well enough, and it wasn't all that hairy to implement after all :)

**Comment by nicolaskruchten** [comment]
@bhogan-mitre in answer to your question about the suffix, I actually think that setting a tickformat will control that suffix.

**Comment by bhogan-mitre** [comment]
I noticed that when I was playing around in the dev app as well.  Very nice!  Thank you.
