### ISSUE TITLE
Tick Labels: provide a way to input custom Prefix & Suffix

### ISSUE THREAD

**Issue by timopulkkinen** [plotly/react-chart-editor#686]
Hi,

There is a drop-down that allows user to select a "custom" prefix or suffix, but there is no place to input such one.

**Comment by dmt0** [comment]
Hi there, thanks for your input!
There's a fix coming in the next version bump!

**Comment by nicolaskruchten** [comment]
Actually this came out in v0.25.0, which was already up on NPM when you posted this issue... are you having problems with that version or...? I know we haven't updated the demo in a while, we've been heads-down working on the releases :)

**Comment by timopulkkinen** [comment]
Oops, didn't notice 0.25.0, was still on 0.24.1 - boy, you're creating releases quickly.  I'll give it a go!

**Comment by timopulkkinen** [comment]
Ok, this works as described in the newer version. Thanks for the great lib!
