### ISSUE TITLE
TraceRequiredPanel should have link to create

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#688]
"Create" should be clickable and cause navigation to the create panel. This should be a generic-ish solution as we'll want to use it in a couple of other places

![image](https://user-images.githubusercontent.com/203523/44105583-024127dc-9fa7-11e8-9d27-054225ebcf24.png)

**Comment by dmt0** [comment]
Should we just remove all panels that are not relevant (#689 ), than we don't need this panel at all

**Comment by nicolaskruchten** [comment]
No I want users to see at least some of what “will be” available once they
add a trace. So let’s just remove the ones I listed: sliders, menus, color
bars, transforms, only if they don’t apply in the given case.
