### ISSUE TITLE
Don't show useless ColorBar and Transform folds

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#695]
Now that we don't let users see the Color Bar or Transform panels at all if they're 100% useless we can go one final step further and just not render the folds for the traces where nothing is possible, so users should never ever see "no color bar for this trace" or "no transforms possible here" or whatever.

**Comment by dmt0** [comment]
Are those really useless? Our support for transforms for example is quite arbitrary right now. It's missing on a lot of trace types where it could theoretically be implemented. I think we should rather have a more descriptive message on those folds. For transforms it could be a list of trace types that are supported. For Colorbar - well nobody specifically needs a colorbar, so maybe we can kill that one.

**Comment by nicolaskruchten** [comment]
Well if I have a scatter trace and a pie trace, and I go to transforms, it's pretty useless for me to see a pie-trace fold that says "I'm useless" :)

**Comment by dmt0** [comment]
But if I have a 3d trace with no 2d array data, that has no reason not to have transforms?
