### ISSUE TITLE
hoverlabel config

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#721]
This exists in `layout` and in `data` but right now it looks like bgcolor etc aren't populated in fulldata?

**Comment by nicolaskruchten** [comment]
OK, not blocked. Let's work around this at the editor level...

Here's what we need:

1. ColorPicker needs to be able to handle `null` or missing values by showing some text saying "this color is computed from other parts of the figure but you can 'click here' to override it" at which point it shows the normal picker and forces a value into the field
2. We add this capability to the editor for both the trace and layout-level variants, and tie its visibility to `hoverlabel.font` or something so that it shows up even when the value isn't in fullData, and then the 'empty state' kicks in.

**Comment by dmt0** [comment]
Would be great to know exactly from which "other parts of the figure" do they actually get colors, so I could prepopulate them with whatever is visually there, and not just black/white.
`bgcolor` is clearly from `marker.color`, `bordercolor` and font are white, but where did white come from?
