### ISSUE TITLE
Fold box-sizing

### ISSUE THREAD

**Issue by bhogan-mitre** [plotly/react-chart-editor#745]
Fold `height` is being set explicitly, but `box-sizing` is not specified.  This is leading to an issue in my application as `box-sizing` is being inherited as `border-box` from another library.  Would it be possible to protect fold height by explicitly setting `box-sizing: content-box`?  Thanks for considering.

https://github.com/plotly/react-chart-editor/blob/master/src/styles/components/containers/_fold.scss#L13

![2018-09-19_05-36-06](https://user-images.githubusercontent.com/32336739/45745792-9d828080-bbcf-11e8-8882-7a025f4157b0.png)

![2018-09-19_05-39-13](https://user-images.githubusercontent.com/32336739/45745809-a3786180-bbcf-11e8-8f77-6b8891beeef8.png)

**Comment by nicolaskruchten** [comment]
At this point we're not really going to mess with the CSS within this repo all that much, but most issues of this type should be resolvable by setting external CSS, potentially with `*` selectors.

**Comment by bhogan-mitre** [comment]
Cool, thank you.  I was struggling to get external CSS carried through to this as a child component from Angular.  If anyone else stumbles upon this, the trick was to set `ViewEncapsulation` to `None`, to override its default `ShadowDom`.  

https://angular.io/api/core/ViewEncapsulation
h/t to https://stackoverflow.com/questions/38798002/angular-2-styling-not-applying-to-child-component
