### ISSUE TITLE
New onDirectUpdate callback triggerered on render

### ISSUE THREAD

**Issue by jonmmease** [plotly/react-chart-editor#751]
It seems that the new `onDirectUpdate` callback added in https://github.com/plotly/react-chart-editor/pull/749 is executed on render as well as on direct manipulation of the plot.  

The JupyterLab extension currently registers an `onUpdate` callback that is executed when the user manipulates the figure using the React widgets. This callback is used to set the state of the extension's `ChartEditor` component.

I tried to register the same callback function with the new `onDirectUpdate` property and ended up in an infinite loop.  I *think* what's happening is that  rendering `PlotlyEditor` is triggering the `onDirectUpdate` callback, which then calls `setState`, which then causes another `render`, and on and on.

Please let me know if I'm misunderstanding something here about the intended use of `onDirectUpdate`. But I'm wondering if it would be possible for `onDirectUpdate` to not execute on the initial render, and only in response to mouse interactions.

Or alternatively, should the `onDirectUpdate` callback function not be calling `setState` at all? Because the plotly figure was already updated internally?

Thanks!

**Comment by nicolaskruchten** [comment]
Ah yeah I hadn’t thought about that... probably you shouldn’t use this to
set state and I should rename it onRender :)

**Comment by jonmmease** [comment]
Ok, well if I just don't set the state everything seems to work fine (See https://github.com/plotly/jupyterlab-chart-editor/pull/24/commits/2374ee94665d7b8b5e725d4904d26fb3efd42092)

**Comment by nicolaskruchten** [comment]
Yeah, the PlotlyEditor keeps its own state so that should work. It’s a
pretty brittle system, prone to infinite loops unfortunately. I’ll still
likely rename that function just for clarity, sorry for the churn.

**Comment by nicolaskruchten** [comment]
See https://github.com/plotly/react-chart-editor/pull/754

**Comment by nicolaskruchten** [comment]
OK, this change was published as v0.31.1
