### ISSUE TITLE
Trace uid not generated

### ISSUE THREAD

**Issue by dmossie** [plotly/react-chart-editor#765]
Hey there,

When I create a new trace using plotly.js@1.41.3, it is not generated with a uid.
I downgraded to plotly.js@1.35.2 and it worked fine.

I am not sure if this is a compatibility issue or a plotly.js issue.

**Comment by dmt0** [comment]
This change was introduced in [1.39](https://github.com/plotly/plotly.js/releases/tag/v1.39.0) of plotly.js. You can see the motivation for it in [this PR](https://github.com/plotly/plotly.js/pull/2681)

**Comment by dmossie** [comment]
Hey @dmt0  - thanks for your response. Do you know if it is possible to get them to show up again? I want to upgrade to the newest version of all the plotly packages, but I rely on the trace UIDs for some business specific customization's I have made.

**Comment by dmt0** [comment]
You can't really get them in `data`, but they are still in  `fullData`.

**Comment by dmossie** [comment]
Thanks @dmt0 
Do you know how to go about accessing fullData? 
Also - is it possible to access outside the editor - such as using the onUpdate prop?

**Comment by dmt0** [comment]
`graphDiv._fullData`
Where graphDiv is the reference to the <div> where plotly.js lives.
Basically it's a structure that's in plotly.js library, not react-chart-editor, so yes, you can access it anywhere.
