### ISSUE TITLE
Atlas Maps - the ability to define the "Map Region" and the "Projection" is missing 

### ISSUE THREAD

**Issue by priyatharsan** [plotly/react-chart-editor#801]
It was available in the older version: 

<img width="955" alt="select-map-region" src="https://user-images.githubusercontent.com/25846124/49176055-0137d100-f318-11e8-80f2-d4d5f8bfb21b.png">

I think it would be good to have that feature back, although it is still possible to define it via JSON tree.

**Comment by nicolaskruchten** [comment]
It's in Subplots:

![image](https://user-images.githubusercontent.com/203523/49179123-9a1e1a80-f31f-11e8-99eb-5c7e6a94f845.png)
