### ISSUE TITLE
Ability to pass event handlers to react-plotly.js

### ISSUE THREAD

**Issue by pmalde** [plotly/react-chart-editor#805]
Firstly thanks for build this fantastic component. Is it possible to pass an function to the event handler of the underlying react-plotly.js component? At the moment I am having to bind the handler in the componentDidMount function. It would be far nicer to pass it through the props as we currently do for the onUpdate function. I’m fairly new to JavaScript and React but would happily take a stab at developing the changes (with some assistance), since I haven’t really contributed to GitHub projects before.

Thanks
Preyesh

**Comment by nicolaskruchten** [comment]
Glad you like this component!

Can you tell us a bit more about what you're trying to do, before we get into the details of 'how' ? :)

**Comment by pmalde** [comment]
I’m using the react-chart-editor to visualise data from our analytics engine. The plots can then be customised through the editor. One feature we would like is that when a user clicks on a subplot, it enlarges into a modal panel that allows them to view the plot in more detail. To do this I originally was intending to add a function to the react-plotly component via the onClick prop. However, I cannot see a way of doing that through the react-chart-editor.

**Comment by nicolaskruchten** [comment]
I see. You will probably need to not use the built-in `PlotlyEditor` component but rather copy it and modify it to taste... It's pretty short: https://github.com/plotly/react-chart-editor/blob/master/src/PlotlyEditor.js

In there you see you have direct access to the `this.PlotComponent` component, which is an instance of the `react-plotly.js`-provided component, to which you can attach whatever events you like.

**Comment by pmalde** [comment]
Ah, I see. Thanks for the guidance.

**Comment by pmalde** [comment]
Hi, as suggested I made a copy of the PlotlyEditor, to gain access to the PlotlyComponent. However, now, when I pass data to the new PlotlyEditor component, I seem to have an additional empty plot in my app and my rendered plot isn't connected to the editor. 

<img width="1494" alt="screenshot 2018-12-17 at 12 22 56" src="https://user-images.githubusercontent.com/7373860/50086978-b1ea0f80-01f6-11e9-9175-8373bdd23674.png">

Is there something I'm doing wrong here?

https://github.com/pmalde/react-chart-editor-issue

**Comment by VeraZab** [comment]
Yes : ) 

You're importing EditorControls as if they were the main export of the library, but the main export is PlotlyEditor (https://github.com/plotly/react-chart-editor/blob/master/src/index.js#L184), which includes both controls and the Plot.

You can fix your example by doing `import { EditorControls } from "react-chart-editor";`

**Comment by pmalde** [comment]
Thanks! Classic newbie error. Still working my way around JS and React!
