### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dwinston** [plotly/react-chart-editor#806]
The README says
> © 2018 Plotly, Inc. MIT License.

but this is not the same as actually having the text of [the MIT license](https://opensource.org/licenses/MIT) explicit and included, either in the README or as a top-level LICENSE file.

Can you please clarify whether this software has an open-source license and, if so, what it is exactly?

Thanks!

**Comment by nicolaskruchten** [comment]
Yikes! That is an oversight. Yes, this is MIT-licensed and I'll merge the license in as soon as CI passes :)

Thanks for the nudge!
