### ISSUE TITLE
Showcase/example page not working

### ISSUE THREAD

**Issue by EndiM** [plotly/react-chart-editor#833]
Link in the repository description - https://plotly.github.io/react-chart-editor - not working.
Here is screenshot - https://cl.ly/7612587354ac

**Comment by dmt0** [comment]
Works fine for me:
![image](https://user-images.githubusercontent.com/2717746/51152929-115e2e00-183c-11e9-8e33-692d05de6489.png)
Are you selecting a specific mock? Some of them are known not to work.

**Comment by EndiM** [comment]
It seems to work now, I didn't get to enter the page it just flickered and threw error, here is short recording - https://cl.ly/7bed054bce6f
