### ISSUE TITLE
geo layout attributes only visible in subplots tab

### ISSUE THREAD

**Issue by cldougl** [plotly/react-chart-editor#851]
It took me a pretty long time/a few tries to find the `geo` attributes (`projection`, map options, ) when creating a map, it looks like those options are currently available in the Subplot tab:
![screen shot 2019-02-20 at 4 57 17 pm](https://user-images.githubusercontent.com/2789078/53127541-ae457280-3530-11e9-9cbe-783ea32deb29.png)

I'm not sure if this is a bug or was intended but can we consider adding these features to one of the style tabs, I don't think it makes sense in the subplots section as users won't visit that section when plotting only a single trace

cc @VeraZab @dmt0

**Comment by nicolaskruchten** [comment]
This is by design because these are subplot level attrs... ie you can have two maps so we can’t put them in style

**Comment by nicolaskruchten** [comment]
We could consider a Geo panel though

**Comment by cldougl** [comment]
In that case perhaps there could be a message similar to the subplot message to push users over there when creating a map, however I think a geo panel makes a little more sense. It would be interesting to know if it's more common to make a single map or subplot maps.

**Comment by nicolaskruchten** [comment]
Certainly it’s more common to make a simple map of course

**Comment by nicolaskruchten** [comment]
But we can’t just prevent the editing of multiple subplot options just because of that :)

**Comment by cldougl** [comment]
> we can’t just prevent the editing of multiple subplot options just because of that :)

sure, but it seems like in that case it would be useful to have a message similar to that posted when creating subplots directing to that tab:
<img width="668" alt="screen shot 2019-02-20 at 8 29 52 pm" src="https://user-images.githubusercontent.com/2789078/53136802-59185980-354e-11e9-83e0-af57411b7bd9.png">

though imo a geo tab would be the best solution as it does seem counterintuitive to style geo attributes for a single map in the subplot tab

**Comment by nicolaskruchten** [comment]
Let's go with a Style/Geo tab that hides if there are no scattergeo or choropleth traces and contains a subplot-accordion for just the geo subplots.
