### ISSUE TITLE
choropleth text controls

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#892]
`choropleth` supports `text` but the widget isn't showing up. The easy fix is to add `choropleth` to the whitelist here https://github.com/plotly/react-chart-editor/blob/master/src/default_panels/StyleTracesPanel.js#L460 but this leads me to question why this is in a `TraceTypeSection` at all... what's the downside to just having this be a `Section`? Can someone dig into this please? :)

**Comment by dmt0** [comment]
The `TraceTypeSection` is there, because we have a `DataSelector` in there - those are unconditionally visible, so we have to hide the section for certain traces.
